// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbtnkxxa9LFI3A7T5qd9b1MLFCg7gzRM',
    appId: '1:192740731119:web:27ef74983e57b5d3c9931a',
    messagingSenderId: '192740731119',
    projectId: 'smart-medicine-dispenser-9fdc5',
    authDomain: 'smart-medicine-dispenser-9fdc5.firebaseapp.com',
    storageBucket: 'smart-medicine-dispenser-9fdc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrgAQCj7kRUDdLIfiYEnwYjIOKzJVvh38',
    appId: '1:192740731119:android:edff8933e761af1cc9931a',
    messagingSenderId: '192740731119',
    projectId: 'smart-medicine-dispenser-9fdc5',
    storageBucket: 'smart-medicine-dispenser-9fdc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7c8wQ7ZJK3DcSO6YYyFt32kLG7alUrQs',
    appId: '1:192740731119:ios:a63967a7fc37f29ac9931a',
    messagingSenderId: '192740731119',
    projectId: 'smart-medicine-dispenser-9fdc5',
    storageBucket: 'smart-medicine-dispenser-9fdc5.firebasestorage.app',
    iosBundleId: 'com.example.myDispenserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7c8wQ7ZJK3DcSO6YYyFt32kLG7alUrQs',
    appId: '1:192740731119:ios:a63967a7fc37f29ac9931a',
    messagingSenderId: '192740731119',
    projectId: 'smart-medicine-dispenser-9fdc5',
    storageBucket: 'smart-medicine-dispenser-9fdc5.firebasestorage.app',
    iosBundleId: 'com.example.myDispenserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsbtnkxxa9LFI3A7T5qd9b1MLFCg7gzRM',
    appId: '1:192740731119:web:3f8d7c4c64acf7cfc9931a',
    messagingSenderId: '192740731119',
    projectId: 'smart-medicine-dispenser-9fdc5',
    authDomain: 'smart-medicine-dispenser-9fdc5.firebaseapp.com',
    storageBucket: 'smart-medicine-dispenser-9fdc5.firebasestorage.app',
  );
}
